services:
  ai-uc-content-swarm-ui:
    build:
      target: development
      context: ../repos/ai-uc-content-swarm-ui
    ports:
      - '3000:3000'
    links:
      - "localstack:localstack"
      - 'redis:redis'
    depends_on:
      localstack:
        condition: service_healthy
      redis:
        condition: service_started
    env_file:
      - "../.env"
    volumes:
      - ../repos/ai-uc-content-swarm-ui/src/:/home/node/src
      - ../repos/ai-uc-content-swarm-ui/package.json:/home/node/package.json
    environment:
      PORT: 3000
      NODE_ENV: development
      REDIS_HOST: redis
      USE_SINGLE_INSTANCE_CACHE: true
    networks:
      - ai-uc-content-swarm
