services:
  ai-uc-content-swarm-runtime:
    build:
      context: ../repos/ai-uc-content-swarm-runtime
      target: development
    ports:
      - 8085:8085
    links:
      - "moto:moto"
      - "mongodb:mongodb"
    depends_on:
      moto:
        condition: service_healthy
      mongodb:
        condition: service_started
    env_file:
      - "../.env"
    environment:
      PORT: ${PORT:-8085}
      MONGO_URI: ${MONGO_URI:-mongodb://mongodb:27017/}
      HOST: ${HOST:-0.0.0.0}
      HOST_URL: ${HOST_URL:-http://host.docker.internal:8085}
      LOCALSTACK_URL: ${LOCALSTACK_URL:-http://localhost:5000}
      S3_ENDPOINT: ${S3_ENDPOINT:-http://localhost:5000}
      SQS_ENDPOINT: ${SQS_ENDPOINT:-http://localhost:5000}
    volumes:
      - ../repos/ai-uc-content-swarm-runtime/app:/home/nonroot/app
    develop:
      watch:
        - action: rebuild
          path: ../repos/ai-uc-content-swarm-runtime/pyproject.toml
          target: /home/nonroot/pyproject.toml
    networks:
      - ai-uc-content-swarm
