services:
  moto:
    build:
      context: ./moto
      dockerfile: Dockerfile
    ports:
      - '5000:5000'
    volumes:
      - './moto/startup.sh:/etc/moto/init/ready.d/startup.sh'
    healthcheck:
      test:
        - CMD
        - bash
        - -c
        - "curl -sf http://localhost:5000/moto-api/data.json || exit 1"
      interval: 5s
      timeout: 5s
      start_period: 10s
      retries: 5
    environment:
      AWS_ACCESS_KEY_ID: test
      AWS_SECRET_ACCESS_KEY: test
      AWS_DEFAULT_REGION: eu-west-2
    networks:
      - node-aws-challenge
  mongodb:
    image: mongo:6.0.13
    ports:
      - 27017:27017
    volumes:
      - mongodb-data:/data
    networks:
      - node-aws-challenge
  redis:
    image: redis:7.2.3-alpine3.18
    ports:
      - 6379:6379
    networks:
      - node-aws-challenge
volumes:
  mongodb-data:
networks:
  node-aws-challenge:
    driver: bridge